### PR TITLE
Ft/footer

### PR DESCRIPTION
**Pull request by kareraolivier**
## Fotter

### CODE REVIEW

**Review by devfabien — COMMENTED** [review]
looking good

**Review by devfabien — CHANGES_REQUESTED** [review]
Resolve those conflicts

**Comment by kareraolivier** [comment]
All conflict are resolved

**Comment by kareraolivier** [comment]
> Resolve those conflicts

They are resolved

**Review by devfabien — APPROVED** [review]
Looking good

**Pull request merged**
